"""Project catalog for the Trading Model umbrella API."""

from __future__ import annotations

PROJECTS: list[dict] = [
    {
        "slug": "gbm",
        "id": 1,
        "title": "Geometric Brownian Motion Stock Price Simulator",
        "path": "projects/01-gbm-simulator",
        "summary": "Exact log-Euler GBM paths for NASDAQ-style equity simulation.",
        "math": "dS = μ S dt + σ S dW",
        "default_params": {
            "s0": 100.0,
            "mu": 0.08,
            "sigma": 0.25,
            "t": 1.0,
            "n_steps": 252,
            "n_paths": 8,
            "seed": 42,
        },
    },
    {
        "slug": "mc-options",
        "id": 2,
        "title": "Monte Carlo Option Pricing",
        "path": "projects/02-mc-option-pricing",
        "summary": "Risk-neutral GBM Monte Carlo for European call/put with SE.",
        "math": "C = e^{-rT} E[(S_T − K)+]",
        "default_params": {
            "s0": 100.0,
            "k": 100.0,
            "r": 0.03,
            "sigma": 0.2,
            "t": 1.0,
            "n_steps": 100,
            "n_paths": 20000,
            "option": "call",
            "seed": 42,
        },
    },
    {
        "slug": "brownian",
        "id": 3,
        "title": "Brownian Motion & Random Walk Visualizer",
        "path": "projects/03-brownian-visualizer",
        "summary": "Wiener process, scaled random walks, and quadratic variation.",
        "math": "W_t = lim Σ √Δt Z_i",
        "default_params": {
            "t": 1.0,
            "n_steps": 500,
            "n_paths": 6,
            "drift": 0.0,
            "diffusion": 1.0,
            "seed": 7,
        },
    },
    {
        "slug": "ou",
        "id": 4,
        "title": "Ornstein–Uhlenbeck Mean Reversion",
        "path": "projects/04-ornstein-uhlenbeck",
        "summary": "OU / Vasicek dynamics for spreads, rates, and pairs.",
        "math": "dX = κ(θ − X) dt + σ dW",
        "default_params": {
            "x0": 0.5,
            "kappa": 3.0,
            "theta": 0.0,
            "sigma": 0.4,
            "t": 2.0,
            "n_steps": 500,
            "n_paths": 8,
            "seed": 11,
        },
    },
    {
        "slug": "heston",
        "id": 5,
        "title": "Heston Stochastic Volatility Simulator",
        "path": "projects/05-heston-simulator",
        "summary": "Correlated spot–variance CIR with leverage (ρ < 0).",
        "math": "dS = μS dt + √v S dWˢ ; dv = κ(θ−v)dt + ξ√v dWᵛ",
        "default_params": {
            "s0": 100.0,
            "v0": 0.04,
            "mu": 0.05,
            "kappa": 2.0,
            "theta": 0.04,
            "xi": 0.5,
            "rho": -0.7,
            "t": 1.0,
            "n_steps": 252,
            "n_paths": 6,
            "scheme": "qe",
            "seed": 42,
        },
    },
    {
        "slug": "var",
        "id": 6,
        "title": "Monte Carlo Value-at-Risk Engine",
        "path": "projects/06-monte-carlo-var",
        "summary": "Portfolio VaR / CVaR from correlated Gaussian returns.",
        "math": "VaR_α = −q_α(L) ; CVaR = E[L | L ≥ VaR]",
        "default_params": {
            "notional": 1_000_000.0,
            "horizon_days": 10,
            "n_sims": 20000,
            "confidence": 0.95,
            "weights": [0.3, 0.25, 0.15, 0.15, 0.1, 0.05],
            "tickers": ["QQQ", "SPY", "IWM", "TLT", "GLD", "HYG"],
            "seed": 99,
        },
    },
    {
        "slug": "rough-vol",
        "id": 7,
        "title": "Rough Volatility (Rough Bergomi)",
        "path": "projects/07-rough-volatility",
        "summary": "Fractional kernel / rough Bergomi for short-tenor skew realism.",
        "math": "v_t = ξ₀(t) exp(η√(2H) Z_t − ½η² t^{2H})",
        "default_params": {
            "s0": 100.0,
            "mu": 0.0,
            "hurst": 0.1,
            "eta": 1.5,
            "rho": -0.7,
            "t": 1.0,
            "n_steps": 126,
            "n_paths": 4,
            "xi0_flat": 0.04,
            "seed": 42,
        },
    },
]

SLUG_INDEX = {p["slug"]: p for p in PROJECTS}
